[package]
name = "app_testing"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
zconf = { path = "../zconf" }
serde = { version = "1", features = ["derive"] }
